"""relationship added

Revision ID: 1ec4a21dea6b
Revises: 4fa78a1a0cb8
Create Date: 2022-11-11 15:20:55.698594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec4a21dea6b'
down_revision = '4fa78a1a0cb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
