"""Relantionship on user and order

Revision ID: 3016326256b9
Revises: 1ec4a21dea6b
Create Date: 2022-11-12 10:21:43.574483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3016326256b9'
down_revision = '1ec4a21dea6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_product', 'product', ['product_id'], ['id'])
        batch_op.create_foreign_key('fk_iser', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.drop_column('phonee')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phonee', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('phone')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_iser', type_='foreignkey')
        batch_op.drop_constraint('fk_product', type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
