"""Relantionship  user and order

Revision ID: 64d1c8ed637b
Revises: 3016326256b9
Create Date: 2022-11-12 10:32:42.795310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d1c8ed637b'
down_revision = '3016326256b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
