"""Relantionship for  user and order

Revision ID: 85f5023bd384
Revises: 64d1c8ed637b
Create Date: 2022-11-12 10:38:29.064635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f5023bd384'
down_revision = '64d1c8ed637b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
