"""Relantionship other entitys

Revision ID: c5867aa87b32
Revises: 85f5023bd384
Create Date: 2022-11-12 10:40:57.379178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5867aa87b32'
down_revision = '85f5023bd384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
